version: '3.8'

services:
  web:
    # On utilise l'image hébergée sur Docker Hub, téléchargée sur le VPS
    image: laurentmd5/sse-suivi-ftth:${IMAGE_TAG:-latest}
    container_name: suivi_ftth_web
    restart: always
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=production
      # La clé secrète doit être configurée dans un fichier .env sur le VPS
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=mysql+pymysql://suivi_user:suivi_password@db/suivi_ftth
    depends_on:
      - db
    volumes:
      - uploads_volume:/app/uploads

  db:
    image: mysql:8.0
    container_name: suivi_ftth_db
    restart: always
    ports:
      - "3039:3306"
    environment:
      # Les identifiants MySQL doivent aussi être sécurisés en production
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=suivi_ftth
      - MYSQL_USER=suivi_user
      - MYSQL_PASSWORD=suivi_password
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  db_volume:
  uploads_volume:
