"""Initial migration

Revision ID: 627f1411b5cc
Revises: 
Create Date: 2026-08-19 12:24:58.297053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627f1411b5cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'team_leader'), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.Column('team_leader_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_leader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_foreign_key('fk_users_team_id_teams', 'users', 'teams', ['team_id'], ['id'])
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nd', sa.String(length=20), nullable=False),
    sa.Column('demande_no', sa.String(length=20), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('team_leader_id', sa.Integer(), nullable=False),
    sa.Column('intervention_date', sa.Date(), nullable=False),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('extraction_method', sa.Enum('filename_only', 'filename_ocr', 'manual'), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.Enum('pending', 'validated', 'corrected'), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_leader_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interventions_intervention_date'), ['intervention_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_interventions_nd'), ['nd'], unique=False)
        batch_op.create_index(batch_op.f('ix_interventions_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_interventions_team_leader_id'), ['team_leader_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interventions_validation_status'), ['validation_status'], unique=False)

    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_month', sa.String(length=7), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(length=50), nullable=True),
    sa.Column('total_sav', sa.Integer(), nullable=True),
    sa.Column('total_diag_reor', sa.Integer(), nullable=True),
    sa.Column('total_installation', sa.Integer(), nullable=True),
    sa.Column('total_passage', sa.Integer(), nullable=True),
    sa.Column('total_survey', sa.Integer(), nullable=True),
    sa.Column('total_upgrade', sa.Integer(), nullable=True),
    sa.Column('total_survey_install', sa.Integer(), nullable=True),
    sa.Column('total_modif_interieur', sa.Integer(), nullable=True),
    sa.Column('total_clients', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_month', 'team_id', name='uk_month_team')
    )
    op.create_table('ocr_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_value', sa.String(length=50), nullable=True),
    sa.Column('extraction_pattern', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_logs_intervention_id'), ['intervention_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_logs_intervention_id'))

    op.drop_table('ocr_logs')
    op.drop_table('monthly_reports')
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interventions_validation_status'))
        batch_op.drop_index(batch_op.f('ix_interventions_team_leader_id'))
        batch_op.drop_index(batch_op.f('ix_interventions_task_type'))
        batch_op.drop_index(batch_op.f('ix_interventions_nd'))
        batch_op.drop_index(batch_op.f('ix_interventions_intervention_date'))

    op.drop_table('interventions')
    op.drop_constraint('fk_users_team_id_teams', 'users', type_='foreignkey')
    op.drop_table('teams')
    op.drop_table('users')
    # ### end Alembic commands ###
