"""Add must_change_password

Revision ID: d9f8bfab93f9
Revises: f09366ff3b17
Create Date: 2026-08-21 16:54:53.761782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f8bfab93f9'
down_revision = 'f09366ff3b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['validated_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['team_leader_id'], ['id'])

    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'])

    with op.batch_alter_table('ocr_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'interventions', ['intervention_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['team_leader_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ocr_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
